/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vet.clinic;
import javax.swing.*;

/**
 *
 * @author zzsjzz
 */
public class TelaMenu extends javax.swing.JPanel {
    public TelaMenu(TelaPrincipal telaPrincipal) {
        setLayout(new BoxLayout(this, BoxLayout.Y_AXIS));
        add(new JLabel("Menu Principal"));

        JButton btnCadastro = new JButton("Ir para Cadastro");
        JButton btnConfig = new JButton("Ir para Configurações");
        JButton btnSair = new JButton("Sair");

        add(btnCadastro);
        add(btnConfig);
        add(btnSair);

//        btnCadastro.addActionListener(e -> telaPrincipal.mostrarTela("cadastro"));
//        btnConfig.addActionListener(e -> telaPrincipal.mostrarTela("config"));
//        btnSair.addActionListener(e -> telaPrincipal.mostrarTela("login"));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
