/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vet.clinic;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author caiyo
 */
public class TelaCadAnimal extends javax.swing.JPanel {
    
    private TelaPrincipal telaPrincipal;
    private Tutor tutor; 
    private String dataNasc;
   /**
     * Creates new form TelaCadAnimal
     */
    public TelaCadAnimal(TelaPrincipal telaPrincipal) {
        this.telaPrincipal = telaPrincipal;
        initComponents();
        
        // Quando o painel for exibido, recarrega os tutores
        this.addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentShown(java.awt.event.ComponentEvent e) {
                preencherComboTutores();
            }
        });
    }
    
    private void preencherComboTutores() {
        ArrayList<Tutor> lista = telaPrincipal.getSistema().getTutores();

        // Cria um modelo de String e popula com os nomes
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        for (Tutor t : lista) {
            model.addElement(t.getNome());
        }

        // Atualiza o combo
        cxTutor.setModel(model);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cxRaca = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cxDataNasc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cxNome = new javax.swing.JTextField();
        cxTutor = new javax.swing.JComboBox<>();

        cxRaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxRacaActionPerformed(evt);
            }
        });

        jLabel2.setText("Raça:");

        cxDataNasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxDataNascActionPerformed(evt);
            }
        });

        jLabel3.setText("Data de Nascimento:");

        jLabel4.setText("Tutor:");

        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome:");

        cxNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxNomeActionPerformed(evt);
            }
        });

        cxTutor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cxTutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxTutorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cxDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cxTutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(176, 176, 176)
                        .addComponent(jButton1))
                    .addComponent(cxNome, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(cxRaca, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cxNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cxRaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(10, 10, 10)
                .addComponent(cxDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(cxTutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cxRacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxRacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxRacaActionPerformed

    private void cxDataNascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxDataNascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxDataNascActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(cxNome.getText().trim().isEmpty() ||
            cxRaca.getText().trim().isEmpty() ||
            cxDataNasc.getText().trim().isEmpty()){

            JOptionPane.showMessageDialog(this, "Por favor, preencha todos os campos!", "Campos obrigatórios", JOptionPane.WARNING_MESSAGE);

        }else{
            String nomeSelecionado = (String) cxTutor.getSelectedItem();

            Tutor tutorSelecionado = null;
            for (Tutor t : telaPrincipal.getSistema().getTutores()) {
                if (t.getNome().equals(nomeSelecionado)) {
                    tutorSelecionado = t;
                    break;
                }
            }

            if (tutorSelecionado == null) {
                JOptionPane.showMessageDialog(this,
                    "Erro: tutor não encontrado!",
                    "Seleção inválida",
                    JOptionPane.ERROR_MESSAGE);
                return;
            }                      
                    
            Animal animal = new Animal(cxNome.getText(), cxRaca.getText(), cxDataNasc.getText(), tutorSelecionado);
            telaPrincipal.getSistema().getAnimais().add(animal);
            
            cxNome.setText("");
            cxRaca.setText("");
            cxDataNasc.setText("");
            cxTutor.setSelectedIndex(-1);  // sem seleção
            
            JOptionPane.showMessageDialog(this, "Animal cadastrado com sucesso!");
            telaPrincipal.mostrarTela("telaMenu");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cxNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxNomeActionPerformed

    private void cxTutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxTutorActionPerformed
        
    }//GEN-LAST:event_cxTutorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cxDataNasc;
    private javax.swing.JTextField cxNome;
    private javax.swing.JTextField cxRaca;
    private javax.swing.JComboBox<String> cxTutor;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
