/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vet.clinic;

import java.time.DateTimeException;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author isabel
 */
public class TelaRegConsulta extends javax.swing.JPanel {
    TelaPrincipal telaPrincipal;
    /**
     * Creates new form TelaRegConsulta
     */
    public TelaRegConsulta(TelaPrincipal telaPrincipal) {
        this.telaPrincipal = telaPrincipal;
        initComponents();
        
        // Quando o painel for exibido, recarrega os tutores
        this.addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentShown(java.awt.event.ComponentEvent e) {
                preencherComboTutores();
            }
        });
    }
    
    private void preencherComboTutores() {
        ArrayList<Animal> animais = telaPrincipal.getSistema().getAnimais();
        ArrayList<Veterinario> vets = telaPrincipal.getSistema().getVeterinarios();

        // Cria um modelo de String e popula com os nomes
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        for (Animal a : animais) {
            model.addElement(a.getNome());
        }
        
        DefaultComboBoxModel<String> model2 = new DefaultComboBoxModel<>();
        for (Veterinario v : vets) {
            model2.addElement(v.getNome());
        }

        // Atualiza o combo
        cxAnimal.setModel(model);
        cxVet.setModel(model2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cxAnimal = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cxDia = new javax.swing.JTextField();
        cxMes = new javax.swing.JTextField();
        cxAno = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cxVet = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        cxDiagnostico = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        cxProblema = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        cxMedicamento = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("Animal");

        cxAnimal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cxAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxAnimalActionPerformed(evt);
            }
        });

        jLabel3.setText("Diagnostico");

        jLabel4.setText("Medicamentos");

        jLabel5.setText("Data");

        cxDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxDiaActionPerformed(evt);
            }
        });

        cxMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxMesActionPerformed(evt);
            }
        });

        jLabel6.setText("Veterinário");

        cxVet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cxDiagnostico.setColumns(20);
        cxDiagnostico.setRows(5);
        jScrollPane4.setViewportView(cxDiagnostico);

        cxProblema.setColumns(20);
        cxProblema.setRows(5);
        jScrollPane5.setViewportView(cxProblema);

        jLabel2.setText("Problema");

        cxMedicamento.setColumns(20);
        cxMedicamento.setRows(5);
        jScrollPane6.setViewportView(cxMedicamento);

        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cxDia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cxMes, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cxAno, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(cxAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(cxVet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(124, 124, 124))
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(12, 12, 12))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cxAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cxVet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cxDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cxMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cxAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(40, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cxAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxAnimalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxAnimalActionPerformed

    private void cxDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxDiaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         // Verifica se um animal foi selecionado
        if (cxAnimal.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Selecione um animal.");
            return;
        }

        // Verifica se um veterinário foi selecionado
        if (cxVet.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Selecione um veterinário.");
            return;
        }

        // Verifica se problema foi preenchido
        if (cxProblema.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Preencha o campo de problema.");
            return;
        }

        // Verifica se diagnóstico foi preenchido
        if (cxDiagnostico.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Preencha o campo de diagnóstico.");
            return;
        }

        // Verifica se dia, mês e ano foram preenchidos e são válidos
        String diaStr = cxDia.getText().trim();
        String mesStr = cxMes.getText().trim();
        String anoStr = cxAno.getText().trim();

        if (diaStr.isEmpty() || mesStr.isEmpty() || anoStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Preencha dia, mês e ano.");
            return;
        }

        int dia, mes, ano;
        try {
            dia = Integer.parseInt(diaStr);
            mes = Integer.parseInt(mesStr);
            ano = Integer.parseInt(anoStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Data inválida: apenas números.");
            return;
        }

        // Validação de data real
        try {
            LocalDate.of(ano, mes, dia);
        } catch (DateTimeException e) {
            JOptionPane.showMessageDialog(this, "Data inválida: " + e.getMessage());
            return;
        }

        // Se chegou aqui, todos os dados estão válidos
        JOptionPane.showMessageDialog(this, "Dados válidos!");
        
        // Recupera os valores dos campos
        String problema = cxProblema.getText().trim();
        String diagnostico = cxDiagnostico.getText().trim();
        String medicamentos = cxMedicamento.getText().trim();
        LocalDate data = LocalDate.of(ano, mes, dia);
        
        String nomeSelecionado = (String) cxVet.getSelectedItem();

        Veterinario vet = null;
        for (Veterinario v : telaPrincipal.getSistema().getVeterinarios()) {
            if (v.getNome().equals(nomeSelecionado)) {
                vet = v;
                break;
            }
        }

        if (vet == null) {
            JOptionPane.showMessageDialog(this, "Veterinário não encontrado.");
            return;
        }


        // Cria a consulta
        Consulta novaConsulta = new Consulta(problema, diagnostico, medicamentos, data, vet);

       String nomeSelecionad = (String) cxAnimal.getSelectedItem();

        Animal animal = null;
        for (Animal a : telaPrincipal.getSistema().getAnimais()) {
            if (a.getNome().equals(nomeSelecionad)) {
                animal = a;
                break;
            }
        }

        if (animal == null) {
            JOptionPane.showMessageDialog(this, "Animal não encontrado.");
            return;
        }

        animal.adicionarConsulta(novaConsulta);
        
        cxMedicamento.setText("");
        cxDiagnostico.setText("");
        cxProblema.setText("");
        cxDia.setText("");
        cxMes.setText("");
        cxAno.setText("");
        cxAnimal.setSelectedIndex(-1);
        cxVet.setSelectedIndex(-1);
        
        telaPrincipal.mostrarTela("telaMenu");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cxMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxMesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cxAnimal;
    private javax.swing.JTextField cxAno;
    private javax.swing.JTextField cxDia;
    private javax.swing.JTextArea cxDiagnostico;
    private javax.swing.JTextArea cxMedicamento;
    private javax.swing.JTextField cxMes;
    private javax.swing.JTextArea cxProblema;
    private javax.swing.JComboBox<String> cxVet;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    // End of variables declaration//GEN-END:variables
}
